export default [{
        "AppId": 180302,
        "Title": "登陆",
        "NavigationId": 10000,
        "ParentID": 0,
        "Url": "/login",
        "Path": "pages/Login",
        "Iconurl": "",
        "CreateTime": "2017-07-14 10:05:05",
        "ChildNavigations": null,
        "Level": 1
    },
    {
        "AppId": 180302,
        "Title": "404",
        "NavigationId": 10001,
        "ParentID": 0,
        "Url": "*",
        "Path": "components/Page404",
        "Iconurl": "",
        "CreateTime": "2017-07-14 10:05:05",
        "ChildNavigations": null,
        "Level": 1
    },
    {
        "AppId": 180302,
        "Title": "修改密码",
        "NavigationId": 10002,
        "ParentID": 0,
        "Url": "/updatePwd",
        "Path": "pages/UpdatePwd",
        "Iconurl": "",
        "CreateTime": "2017-10-31 10:05:05",
        "ChildNavigations": null,
        "Level": 1
    },
    {
        "AppId": 180302,
        "Title": "财经云",
        "NavigationId": 10003,
        "ParentID": 0,
        "Url": "/home",
        "Path": "pages/Home",
        "Iconurl": "",
        "CreateTime": "2017-12-18 10:46:43",
        "ChildNavigations": null,
        "Level": 1
    },
    {
        "AppId": 180302,
        "Title": "选择课程大纲模板",
        "NavigationId": 10004,
        "ParentID": 0,
        "Url": "/syllabus/manage/template",
        "Path": "components/SyllabusManage/SyllabusModuleOptTemplate",
        "Iconurl": "",
        "CreateTime": "2017-12-18 10:46:43",
        "ChildNavigations": null,
        "parenttitle": [
            { name: "课程大纲管理", url: '' },
            { name: "课程大纲列表", url: '/syllabus/manage/list' },
            { name: "编辑课程大纲", url: '' },
        ]
    },

    {
        "AppId": 180302,
        "Title": "编辑课程大纲",
        "NavigationId": 10005,
        "ParentID": 0,
        "Url": "/syllabus/manage/edit",
        "Path": "components/SyllabusManage/SyllabusModuleEdit",
        "Iconurl": "",
        "CreateTime": "2017-12-18 10:46:43",
        "ChildNavigations": null,
        "parenttitle": [
            { name: "课程大纲管理", url: '' },
            { name: "课程大纲列表", url: '/syllabus/manage/list' },
            { name: "编辑课程大纲", url: '' },
        ]
    },
    {
        "AppId": 180302,
        "Title": "课程基本设置",
        "NavigationId": 10006,
        "ParentID": 0,
        "Url": "/course/manage/basic/set",
        "Path": "components/CourseManage/CourseModuleBasicSet",
        "Iconurl": "",
        "CreateTime": "2017-12-18 10:46:43",
        "ChildNavigations": null,
        "parenttitle": [
            { name: "课程管理", url: '' },
            { name: "课程列表", url: '/course/manage/list' },
            { name: "课程基本设置", url: '' },
        ]
    },
    {
        "AppId": 180302,
        "Title": "课程内容",
        "NavigationId": 10007,
        "ParentID": 0,
        "Url": "/course/manage/content/set",
        "Path": "components/CourseManage/CourseModuleContentSet",
        "Iconurl": "",
        "CreateTime": "2017-12-18 10:46:43",
        "ChildNavigations": null,
        "parenttitle": [
            { name: "课程管理", url: '' },
            { name: "课程列表", url: '/course/manage/list' },
            { name: "课程内容", url: '' },
        ]
    },
    {
        "AppId": 180302,
        "Title": "新增视频",
        "NavigationId": "createVideo",
        "ParentID": 0,
        "Url": "/resource/video/create",
        "Path": "components/resourceCenter/videoManage/resourceModuleVideoCreate",
        "Iconurl": "",
        "CreateTime": "2017-12-18 10:46:43",
        "ChildNavigations": null,
        "parenttitle": [
            { name: "资源中心", url: '' },
            { name: "视频管理", url: '' },
            { name: "视频列表", url: '/resource/video/list' },
            { name: "新增视频", url: '' },
        ]
    },
    {
        "AppId": 180302,
        "Title": "编辑视频",
        "NavigationId": "editVideo",
        "ParentID": 0,
        "Url": "/resource/video/edit",
        "Path": "components/resourceCenter/videoManage/resourceModuleVideoEdit",
        "Iconurl": "",
        "CreateTime": "2017-12-18 10:46:43",
        "ChildNavigations": null,
        "parenttitle": [
            { name: "资源中心", url: '' },
            { name: "视频管理", url: '' },
            { name: "视频列表", url: '/resource/video/list' },
            { name: "编辑视频", url: '' },
        ]
    },
    {
        "AppId": 180302,
        "Title": "预览视频",
        "NavigationId": "previewVideo",
        "ParentID": 0,
        "Url": "/resource/video/preview",
        "Path": "components/resourceCenter/videoManage/resourceModuleVideoPreview",
        "Iconurl": "",
        "CreateTime": "2017-12-18 10:46:43",
        "ChildNavigations": null,
        "parenttitle": [
            { name: "资源中心", url: '' },
            { name: "视频管理", url: '' },
            { name: "视频列表", url: '/resource/video/list' },
            { name: "预览视频", url: '' },
        ]
    },
    {
      "AppId": 180302,
      "Title": "课中交互",
      "NavigationId": "interactiveVideo",
      "ParentID": 0,
      "Url": "/resource/video/interactive",
      "Path": "components/resourceCenter/videoManage/resourceModuleVideoInteractive",
      "Iconurl": "",
      "CreateTime": "2017-12-18 10:46:43",
      "ChildNavigations": null,
      "parenttitle": [
          { name: "资源中心", url: '' },
          { name: "视频管理", url: '' },
          { name: "视频列表", url: '/resource/video/list' },
          { name: "课中交互", url: '' },
      ]
    },
    {
        "AppId": 180302,
        "Title": "新增讲义",
        "NavigationId": "createHandout",
        "ParentID": 0,
        "Url": "/resource/handout/create",
        "Path": "components/resourceCenter/handoutManage/resourceModuleHandoutCreate",
        "Iconurl": "",
        "CreateTime": "2017-12-18 10:46:43",
        "ChildNavigations": null,
        "parenttitle": [
            { name: "资源中心", url: '' },
            { name: "讲义管理", url: '' },
            { name: "讲义列表", url: '/resource/handout/list' },
            { name: "新增讲义", url: '' },
        ]
    }, {
        "AppId": 180302,
        "Title": "编辑讲义",
        "NavigationId": "editHandout",
        "ParentID": 0,
        "Url": "/resource/handout/edit",
        "Path": "components/resourceCenter/handoutManage/resourceModuleHandoutEdit",
        "Iconurl": "",
        "CreateTime": "2017-12-18 10:46:43",
        "ChildNavigations": null,
        "parenttitle": [
            { name: "资源中心", url: '' },
            { name: "讲义管理", url: '' },
            { name: "讲义列表", url: '/resource/handout/list' },
            { name: "新增讲义", url: '' },
        ]
    },
    {
      "AppId": 180302,
      "Title": "新增资源组",
      "NavigationId": "createResourceGroup",
      "ParentID": 0,
      "Url": "/resource/resource-group/create",
      "Path": "components/resourceCenter/resourceGroupManage/resourceModuleResourceGroupCreate",
      "Iconurl": "",
      "CreateTime": "2017-12-18 10:46:43",
      "ChildNavigations": null,
      "parenttitle": [
          { name: "资源中心", url: '' },
          { name: "视频管理", url: '' },
          { name: "视频列表", url: '/resource/resource-group/list' },
          { name: "新增视频", url: '' },
      ]
  },
  {
      "AppId": 180302,
      "Title": "编辑资源组",
      "NavigationId": "editResourceGroup",
      "ParentID": 0,
      "Url": "/resource/resource-group/edit",
      "Path": "components/resourceCenter/resourceGroupManage/resourceModuleResourceGroupEdit",
      "Iconurl": "",
      "CreateTime": "2017-12-18 10:46:43",
      "ChildNavigations": null,
      "parenttitle": [
          { name: "资源中心", url: '' },
          { name: "视频管理", url: '' },
          { name: "视频列表", url: '/resource/resource-group/list' },
          { name: "编辑视频", url: '' },
      ]
  },
    {
        "AppId": 180302,
        "Title": "新增知识点",
        "NavigationId": 10010,
        "ParentID": 0,
        "Url": "/resource/knowledge/create",
        "Path": "components/resourceCenter/resourceModuleKnowledgeCreate",
        "Iconurl": "",
        "CreateTime": "2017-12-18 10:46:43",
        "ChildNavigations": null,
        "parenttitle": [
            { name: "资源中心", url: '' },
            { name: "知识图谱", url: '' },
            { name: "知识点汇总", url: '/KnowledgeList' },
            { name: "新增知识点", url: '' },
        ]
    },
    {
        "AppId": 180302,
        "Title": "编辑知识点",
        "NavigationId": 10011,
        "ParentID": 0,
        "Url": "/resource/knowledge/edit",
        "Path": "components/resourceCenter/resourceModuleKnowledgeEdit",
        "Iconurl": "",
        "CreateTime": "2017-12-18 10:46:43",
        "ChildNavigations": null,
        "parenttitle": [
            { name: "资源中心", url: '' },
            { name: "知识图谱", url: '' },
            { name: "知识点汇总", url: '/KnowledgeList' },
            { name: "编辑知识点", url: '' },
        ]
    }
]
