export const cluesTable = [
    //     {
    //     key: 'MainPhone',
    //     wh: '150',
    //     sort:false,
    //     label: '手机',
    // }, 
    {
        key: 'ContactsNo',
        wh: '150',
        sort: false,
        label: '国际电话',
    }, {
        key: 'CourseType',
        wh: '130',
        sort: false,
        label: '感兴趣项目',
    }, {
        key: 'ClueOwner',
        wh: '135',
        sort: true,
        label: '线索所属人',
    }, {
        key: 'ClueStatus',
        wh: '130',
        sort: true,
        label: '线索状态',
    }, {
        key: 'IntentionGrade',
        wh: '115',
        sort: false,
        label: '客户意向度',
    }, {
        key: 'UrgencyName',
        wh: '135',
        sort: false,
        label: '客户沟通紧急度',
    }, {
        wh: '120',
        key: 'Province_City',
        sort: false,
        label: '所在省市',
    }, {
        key: 'SchoolName',
        wh: '125',
        sort: true,
        label: '学校',
        Excess: false
    }, {
        key: 'Major',
        wh: '125',
        sort: true,
        label: '专业',
        Excess: false
    }, {
        key: 'EnrollmentYearStr',
        wh: '135',
        sort: true,
        label: '入学年份',
        Excess: false
    }, {
        wh: '120',
        key: 'Profession',
        sort: false,
        label: '职业状态',
    }, {
        wh: '125',
        key: 'TrafficState',
        sort: true,
        label: '话务状态',
    }, {
        key: 'ClueLabelStr',
        wh: '125',
        sort: false,
        label: '关联标签',
    }, {
        key: 'FirstChannelCode',
        wh: '125',
        sort: false,
        label: '首次客户来源',
    }, {
        key: 'EffectivelyChannelCode',
        wh: '125',
        sort: false,
        label: '末次客户来源',
    }, {
        key: 'ChannelCodeSub',
        wh: '120',
        sort: false,
        label: '营销计划',
    }, {
        key: 'SourceChannelName',
        wh: '110',
        sort: false,
        label: '来源渠道',
    }, {
        key: 'ClueQuality',
        wh: '125',
        sort: false,
        label: '优质线索类型',
    }, {
        key: 'CommunicatContent',
        wh: '165',
        sort: false,
        label: '沟通记录',
    }, {
        key: 'CustomNo',
        wh: '165',
        sort: false,
        label: '客户编号',
    }, {
        key: 'id',
        wh: '165',
        sort: false,
        label: '线索ID',
    }, {
        key: 'Create_By',
        wh: '110',
        sort: false,
        label: '线索创建人',
    }, {
        key: 'RepeatConsultationOwner',
        wh: '110',
        sort: false,
        label: '重复咨询人',
    }, {
        key: 'ClueSource',
        wh: '110',
        sort: false,
        label: '线索来源人',
    }, {
        key: 'RepeatConsultationTime',
        wh: '170',
        sort: false,
        label: '重复咨询时间',
    }, {
        key: 'RepeatConsultationCount',
        wh: '125',
        sort: false,
        label: '重复咨询次数',
    }, {
        key: 'Create_Time',
        wh: '170',
        sort: true,
        label: '创建时间',
    }, {
        key: 'LastCommunicateTime',
        wh: '170',
        sort: true,
        label: '末次沟通时间'
    }, {
        key: 'NextCommunicateTime',
        wh: '170',
        sort: true,
        label: '下次沟通时间',
    }, {
        key: 'ClueOwerGetTime',
        wh: '185',
        sort: true,
        label: '当前所属人获得时间',
    }, {
        key: 'ExamDate',
        wh: '170',
        sort: false,
        label: '考试时间',
    }, {
        key: 'ClueSaleOwner',
        wh: '110',
        sort: false,
        label: '所属销售',
    }, {
        key: 'ClueSchoolManagerOwner',
        wh: '110',
        sort: false,
        label: '所属学管',
    }, {
        key: 'SaleFailureFollowCount',
        wh: '135',
        sort: false,
        label: '销售未跟进天数',
    }, {
        key: 'SaleDialCount',
        wh: '125',
        sort: false,
        label: '销售拨打次数',
    }, {
        key: 'SaleConnetCount',
        wh: '125',
        sort: false,
        label: '销售接通次数',
    }, {
        key: 'SchoolManagerGetTime',
        wh: '170',
        sort: false,
        label: '学管获得时间',
    }, {
        key: 'Old_ClueGuid',
        wh: '100',
        sort: false,
        label: '合并线索',
    }
];
export const cluesSalesTable = [{
    key: 'LastCommunicateTime',
    wh: '115',
    label: '未沟通记录',
}, {
    key: 'NextCommunicateTime',
    wh: '121',
    label: '下次沟通时间',
}, {
    key: 'IntentionGrade',
    wh: '120',
    label: '客户意向度',
}];