export const myClientTable = [{
    key: 'OverseasMobile',
    wh: '140',
    sort: false,
    label: '国际电话',
    Excess: false
}, {
    key: 'CourseTypeName',
    wh: '130',
    sort: false,
    label: '感兴趣项目',
    Excess: false
}, {
    key: 'CommunicatContent',
    wh: '150',
    sort: false,
    label: '沟通记录',
    Excess: true
}, {
    key: 'LastCommunicateTime',
    wh: '170',
    sort: true,
    label: '末次沟通时间',
    Excess: false
}, {
    key: 'NextCommunicateTime',
    wh: '170',
    sort: true,
    label: '下次沟通时间',
    Excess: false
}, {
    key: 'ClueOwnerName',
    wh: '120',
    sort: false,
    label: '线索所属人',
    Excess: false
}, {
    key: 'ClueStatusName',
    wh: '125',
    sort: true,
    label: '线索状态',
    Excess: false
}, {
    wh: '125',
    key: 'TrafficStateName',
    sort: false,
    label: '话务状态',
    Excess: false
}, {
    key: 'Create_ByName',
    wh: '120',
    sort: false,
    label: '线索创建人',
    Excess: false
}, {
    key: 'ClueOwerGetTime',
    wh: '170',
    sort: false,
    label: '所属人获得时间',
    Excess: false
}, {
    key: 'Create_Time',
    wh: '170',
    sort: false,
    label: '创建时间',
    Excess: false
}, {
    key: 'IntentionGradeName',
    wh: '115',
    sort: false,
    label: '客户意向度',
    Excess: false
}, {
    key: 'EffectivelyChannelName',
    wh: '125',
    sort: false,
    label: '末次客户来源',
    Excess: false
}, {
    key: 'ClueQualityName',
    wh: '145',
    sort: true,
    label: '优质线索类型',
    Excess: false
}, {
    key: 'RepeatConsultationOwnerName',
    wh: '120',
    sort: false,
    label: '重复咨询人',
    Excess: false
}, {
    key: 'RepeatConsultationTime',
    wh: '170',
    sort: false,
    label: '重复咨询时间',
    Excess: false
}, {
    key: 'SchoolName',
    wh: '125',
    sort: true,
    label: '学校',
    Excess: false
}, {
    key: 'Major',
    wh: '125',
    sort: true,
    label: '专业',
    Excess: false
}, {
    key: 'ClueLabelStr',
    wh: '125',
    sort: false,
    label: '关联标签',
}, {
    key: 'EnrollmentYearStr',
    wh: '135',
    sort: true,
    label: '入学年份',
    Excess: false
}, {
    key: 'ClueNo',
    wh: '165',
    sort: false,
    label: '线索ID',
    Excess: false
}, {
    key: 'CustomNo',
    wh: '168',
    sort: false,
    label: '客户编号',
    Excess: false
}];