export default [
    {
        "AppId": 180302,
        "Title": "登陆",
        "NavigationId": 10000,
        "ParentID": 0,
        "Url": "/login",
        "Path": "containers/Login",
        "Iconurl": "",
        "CreateTime": "2017-07-14 10:05:05",
        "ChildNavigations": null,
        "Level": 1
    },
    {
        "AppId": 180302,
        "Title": "404",
        "NavigationId": 10001,
        "ParentID": 0,
        "Url": "*",
        "Path": "components/Page404",
        "Iconurl": "",
        "CreateTime": "2017-07-14 10:05:05",
        "ChildNavigations": null,
        "Level": 1
    },
    {
        "AppId": 180302,
        "Title": "修改密码",
        "NavigationId": 10002,
        "ParentID": 0,
        "Url": "/updatePwd",
        "Path": "containers/UpdatePwd",
        "Iconurl": "",
        "CreateTime": "2017-10-31 10:05:05",
        "ChildNavigations": null,
        "Level": 1
    },
    {
        "AppId": 180302,
        "Title": "- 财经云",
        "NavigationId": 10003,
        "ParentID": 0,
        "Url": "/home",
        "Path": "containers/Home",
        "Iconurl": "",
        "CreateTime": "2017-12-18 10:46:43",
        "ChildNavigations": null,
        "Level": 1
    },
    {
        "AppId": 180302,
        "Title": "编辑课程大纲",
        "NavigationId": 10004,
        "ParentID": 0,
        "Url": "/CourseOutlineManage/CourseOutline",
        "Path": "components/CourseOutlineManage/CourseOutline",
        "Iconurl": "",
        "CreateTime": "2017-12-18 10:46:43",
        "ChildNavigations": null,
        "parenttitle": [
            {name: "课程大纲管理", url: ''},
            {name: "课程大纲列表", url: '/CourseOutlineList'},
            {name: "编辑课程大纲", url: 'CourseOutlineManage/CourseOutline'},
        ]
    },

    {
        "AppId": 180302,
        "Title": "课程大纲模块",
        "NavigationId": 10005,
        "ParentID": 0,
        "Url": "/CourseOutlineManage/CourseModule/",
        "Path": "components/CourseOutlineManage/CourseModule",
        "Iconurl": "",
        "CreateTime": "2017-12-18 10:46:43",
        "ChildNavigations": null,
        "parenttitle": [
            {name: "课程大纲管理", url: ''},
            {name: "课程大纲列表", url: '/CourseOutlineList'},
            {name: "编辑课程大纲", url: '/CourseOutlineManage/CourseModule'},
        ]
    },
    {
        "AppId": 180302,
        "Title": "课程基本设置",
        "NavigationId": 10006,
        "ParentID": 0,
        "Url": "/CourseSet",
        "Path": "components/CourseManage/CourseSet",
        "Iconurl": "",
        "CreateTime": "2017-12-18 10:46:43",
        "ChildNavigations": null,
        "parenttitle": [
            {name: "课程管理", url: ''},
            {name: "课程列表", url: '/CourseList'},
            {name: "课程基本设置", url: ''},
        ]
    },
    {
        "AppId": 180302,
        "Title": "课程内容",
        "NavigationId": 10007,
        "ParentID": 0,
        "Url": "/CourseContent",
        "Path": "components/CourseManage/CourseContent",
        "Iconurl": "",
        "CreateTime": "2017-12-18 10:46:43",
        "ChildNavigations": null,
        "parenttitle": [
            {name: "课程管理", url: ''},
            {name: "课程列表", url: '/CourseList'},
            {name: "课程内容", url: ''},
        ]
    },
    {
        "AppId": 180302,
        "Title": "- 新增视频",
        "NavigationId": 10008,
        "ParentID": 0,
        "Url": "/resource/video/create",
        "Path": "components/resourceCenter/addVideo",
        "Iconurl": "",
        "CreateTime": "2017-12-18 10:46:43",
        "ChildNavigations": null,
        "parenttitle": [
            {name: "资源中心", url: ''},
            {name: "视频管理", url: ''},
            {name: "视频列表", url: '/VideoList'},
            {name: "新增视频", url: '/resource/video/create'},
        ]
    },
    {
        "AppId": 180302,
        "Title": "- 新增视频",
        "NavigationId": 10009,
        "ParentID": 0,
        "Url": "/resource/video/edit/:id",
        "Path": "components/resourceCenter/addVideo",
        "Iconurl": "",
        "CreateTime": "2017-12-18 10:46:43",
        "ChildNavigations": null,
        "parenttitle": [
            {name: "资源中心", url: ''},
            {name: "视频管理", url: ''},
            {name: "视频列表", url: '/VideoList'},
            {name: "编辑视频", url: '/resource/video/edit/:id'},
        ]
    },
    {
        "AppId": 180302,
        "Title": "- 新增讲义",
        "NavigationId": 10009,
        "ParentID": 0,
        "Url": "/addHandout",
        "Path": "components/resourceCenter/addHandout",
        "Iconurl": "",
        "CreateTime": "2017-12-18 10:46:43",
        "ChildNavigations": null,
        "parenttitle": [
            {name: "资源中心", url: ''},
            {name: "讲义管理", url: ''},
            {name: "讲义列表", url: '/HandoutList'},
            {name: "新增讲义", url: '/AddHandout'},
        ]
    },
    {
        "AppId": 180302,
        "Title": "- 新增知识点",
        "NavigationId": 10010,
        "ParentID": 0,
        "Url": "/addHandout",
        "Path": "components/resourceCenter/AddKnowledge",
        "Iconurl": "",
        "CreateTime": "2017-12-18 10:46:43",
        "ChildNavigations": null,
        "parenttitle": [
            {name: "资源中心", url: ''},
            {name: "知识图谱", url: ''},
            {name: "知识点汇总", url: '/KnowledgeList'},
            {name: "新增知识点", url: '/AddKnowledge'},
        ]
    },
    {
        "AppId": 180302,
        "Title": "- 编辑知识点",
        "NavigationId": 10011,
        "ParentID": 0,
        "Url": "/editKnowledge",
        "Path": "components/resourceCenter/EditKnowledge",
        "Iconurl": "",
        "CreateTime": "2017-12-18 10:46:43",
        "ChildNavigations": null,
        "parenttitle": [
            {name: "资源中心", url: ''},
            {name: "知识图谱", url: ''},
            {name: "知识点汇总", url: '/KnowledgeList'},
            {name: "编辑知识点", url: '/editKnowledge'},
        ]
    },
    {
        "AppId": 180302,
        "Title": "EP课程学习数据统计",
        "NavigationId": 10012,
        "ParentID": 0,
        "Url": "/EducationalClass",
        "Path": "containers/EducationalClass",
        "Iconurl": "",
        "CreateTime": "2017-12-18 10:46:43",
        "ChildNavigations": null,
        "parenttitle": [
            {name: "班级列表", url: ''},
            {name: "班级列表1", url: '/EducationalClass'},
        ]
    }
]